
GET http://localhost:3001/api/blogs


###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGQwY2RkZDg1ZjhkOGU5Yzc1MGVjNSIsImlhdCI6MTY0NTAyNjYzNywiZXhwIjoxNjQ1MDMwMjM3fQ.dCshNqr6sRcV92Nk9AlfjMLiDKOODlTf2io9mvLv4z0

 {     
    "title": "the channel",
    "author": "the king",
    "url": "http://localhost:3001/api/blogs",
    "likes": 0
}

###

POST   http://localhost:3001/api/blogs
Content-Type: application/json

 {
    "author": "scmkfef",
    "likes": 0
}
###
DELETE  http://localhost:3001/api/blogs/620bd1df4eae72057d9e8e41
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJhNWFhZDFkNjZlNjMyOTVjNDJlNyIsImlhdCI6MTY0NDk0ODA4NywiZXhwIjoxNjQ0OTUxNjg3fQ.eMPFBWc4d7eBAA5fP4lkK3uLMU4GEfJyUqGJ0tA5zhA
###


PUT   http://localhost:3001/api/blogs/61f97e8632b573f236c05465
Content-Type: application/json

 {
    "title": "ade",
    "author": "f9dddd",
    "url": "http://localhost:3001/api/blogs",
    "likes": 8,
    "id": "61f97e8632b573f236c05465"
  }





